### ISSUE TITLE
About the evaluate method

### ISSUE THREAD

**Issue by linWujl** [Wang-Yu-Qing/UTPM#10]
It seems there is a bug in the evaluate function? The predict results have been convert to their source tagid, but in the test dataset, target tags are index, so the precision is always 0 in my result.

![image](https://github.com/Wang-Yu-Qing/UTPM/assets/9161371/a5c2a278-6f16-43d1-b024-478c9977ba2a)

**Comment by Wang-Yu-Qing** [comment]
@linWujl Hi, after you corrected the tagid, did the precision become right?

**Comment by feng20001022** [comment]
Traceback (most recent call last):
  File "/root/fengyongkang/utpm_folder/train_utpm.py", line 97, in <module>
    users_embeds = evaluate(model, test_dataset, tags_embeds, args.U)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fengyongkang/utpm_folder/utils.py", line 425, in evaluate
    _user_embeds = model.forward(pos_tag, pos_cate)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fengyongkang/utpm_folder/models/utpm.py", line 156, in forward
    x = self.attention_forward(pos_tags, pos_cates)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fengyongkang/utpm_folder/models/utpm.py", line 129, in attention_forward
    h0_fea_merged, h1_fea_merged = self.merge_features(i, fea_embeds)   # （batch_size, E）
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fengyongkang/utpm_folder/models/utpm.py", line 107, in merge_features
    h0_fea_merged = self.head_attention(fea_embeds, 0, self.Q, W, B)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fengyongkang/utpm_folder/models/utpm.py", line 86, in head_attention
    matmul_Q = torch.matmul(relued, Q_head).squeeze(dim=[2, 3])  # (batch_size, n)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (800x1 and 8x1)

为什么fea_embeds在h0_fea_merged, h1_fea_merged = self.merge_features(i, fea_embeds)   # （batch_size, E）备注的是（batch，E），传到merge_features里的head_attention里时就当成（batch_size, n, E）了，这个head_attention里的n代表的是什么，导致了维度不匹配
